version: "3"
services:
  app:
    build: .
    container_name: ${APP_NAME}
    env_file:
    - .env
    ports:
      - ${APP_PORT}:5000
    restart: always
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/info"]
      interval: 10s
      timeout: 10s
      retries: 20

networks:
  app_net:
    name: ${APP_NAME}_net
    driver: bridge
